// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package openapi

// basic response
type BasicResponse struct {
	// Detail error message if return code is not OK
	ErrorMsg *string `json:"error_msg,omitempty"`

	// Return code.  Usually 0 means OK.
	ReturnCode int `json:"return_code"`
}
